name: Deploy Website to GitHub Pages
# Performs the following steps:
#   - Builds JavaScript and CSS bundles with Vite (not committed, see .gitignore)
#   - Builds the website with Jekyll 4
#   - Deploys the generated website to GitHub Pages
#
# Requires "Settings > Pages > Build and deployment > Source" to be set to "GitHub Actions"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, but don't cancel an in-progress one
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build JavaScript and CSS bundles with Vite
        run: npm run build

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Build with Jekyll
        run: bundle exec jekyll build -d _site/
        env:
          JEKYLL_ENV: production

      - name: Upload website
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
